### ISSUE TITLE
Typo in class.spferror.php filename

### ISSUE THREAD

**Issue by bugrakoc** [tylerhall/simple-php-framework#23]
Hello tylerhall

The file that contains the SPFError class is named class.sferror.php instead of class.spferror.php, which in turn causes the autoloading to fail and throw the following error:

Fatal error: Uncaught Error: Class 'SPFError' not found in /includes/master.inc.php:34

Thought I'd better let you know. Thanks for sharing your work :)

**Comment by tylerhall** [comment]
Thanks for that! I'll correct it.
